"""Add extended horse columns"""

revision = '288780da9e6d'
down_revision = '0002_prediction_variable_replacement'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horses', sa.Column('odds', sa.String(length=50), nullable=True))
    op.add_column('horses', sa.Column('equipment', sa.String(length=50), nullable=True))
    op.add_column('horses', sa.Column('pedigree_description', sa.String(length=255), nullable=True))
    op.add_column('horses', sa.Column('dob', sa.String(length=50), nullable=True))
    op.add_column('horses', sa.Column('silks', sa.String(length=255), nullable=True))
    op.add_column('horses', sa.Column('stakes', sa.String(length=50), nullable=True))
    op.add_column('horses', sa.Column('sale_price', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horses', 'sale_price')
    op.drop_column('horses', 'stakes')
    op.drop_column('horses', 'silks')
    op.drop_column('horses', 'dob')
    op.drop_column('horses', 'pedigree_description')
    op.drop_column('horses', 'equipment')
    op.drop_column('horses', 'odds')
    # ### end Alembic commands ###
